In [2]:
import torch

Introduction to tensors

In [3]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as int

scalar.item()

7

In [7]:
#vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
 #matrix

matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

creating random tensors

In [22]:
#random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8165, 0.5578, 0.4428, 0.0466],
        [0.8810, 0.8709, 0.5325, 0.1683],
        [0.2891, 0.8596, 0.9309, 0.4292]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#creating random tensor with similar shape of an image

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
#creating random tensors of zeros and ones

random_0_tensor = torch.zeros(size=(3,4))
random_1_tensor = torch.ones(size=(3,4))

random_0_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
random_1_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
random_1_tensor.dtype

torch.float32

creating a range of tensors and tensors like


In [48]:
#creating a range of tensors

one_to_ten = torch.arange(0,10)

In [41]:
torch.__version__

'2.8.0'

In [42]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [49]:
#creating tensor like

ten_zeros = torch.zeros_like(one_to_ten)

print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


dealing with tensor data types

In [60]:
#float 32 tensor

float_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device="mps", requires_grad=False)
float_tensor.dtype

torch.float32

In [61]:
float_tensor

tensor([3., 6., 9.], device='mps:0')

In [62]:
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)