In [3]:
import torch

Introduction to tensors

In [4]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as int

scalar.item()

7

In [7]:
#vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
 #matrix

matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

creating random tensors

In [16]:
#random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7580, 0.9234, 0.9696, 0.8867],
        [0.1217, 0.0871, 0.4275, 0.3241],
        [0.7799, 0.6529, 0.0716, 0.8203]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
#creating random tensor with similar shape of an image

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
#creating random tensors of zeros and ones

random_0_tensor = torch.zeros(size=(3,4))
random_1_tensor = torch.ones(size=(3,4))

random_0_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
random_1_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
random_1_tensor.dtype

torch.float32

creating a range of tensors and tensors like


In [23]:
#creating a range of tensors

one_to_ten = torch.arange(0,10)

In [24]:
torch.__version__

'2.8.0'

In [25]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
#creating tensor like

ten_zeros = torch.zeros_like(one_to_ten)

print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


dealing with tensor data types

In [27]:
#float 32 tensor

float_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32, device="mps", requires_grad=False)
float_tensor.dtype

torch.float32

In [28]:
float_tensor

tensor([3., 6., 9.], device='mps:0')

In [29]:
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [30]:
float_16_tensor * float_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [ ]:
#getting information from tensors



In [32]:
tensor.dtype

torch.int64

In [33]:
tensor.shape

torch.Size([1, 3, 3])

In [34]:
tensor.device

device(type='cpu')

In [35]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2361, 0.1069, 0.4149, 0.1238],
        [0.4819, 0.0410, 0.1387, 0.2573],
        [0.3489, 0.9357, 0.3219, 0.6395]])

In [36]:
some_tensor.shape

torch.Size([3, 4])

In [37]:
some_tensor.dtype

torch.float32

In [38]:
some_tensor.device

device(type='cpu')

In [39]:
#manipulating tensors

t = torch.tensor([1,2,3])
t+10


tensor([11, 12, 13])

In [40]:
t*10

tensor([10, 20, 30])

In [41]:
t-10

tensor([-9, -8, -7])

In [42]:
t/10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
torch.mul(t, 10)

tensor([10, 20, 30])

In [45]:
#matrix multiplication
#element wise

t*t

tensor([1, 4, 9])

In [46]:
torch.matmul(t,t)

tensor(14)

In [48]:
#one of the most common errors of deep learning is shape errors
#inner dimentions must match

t1 = torch.rand(3,2)
t2 = torch.rand(2,3)

torch.matmul(t1,t2)

tensor([[0.2913, 0.5629, 0.3082],
        [0.3731, 0.6335, 0.4103],
        [0.7169, 1.1890, 0.7935]])

In [ ]:
#shapes for tensor multiplication

tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


torch.matmul(tensorA, tensorB)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
#to fix tensor shape issues we can manipulate the shapes using transpose
#it switches the dimentions of a tensor

tensorB.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
torch.matmul(tensorA, tensorB.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [57]:
#tensor aggregation

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
x.min()

tensor(0)

In [59]:
x.max()

tensor(90)

In [62]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [63]:
x.sum()

tensor(450)

In [64]:
#finding positional max and min

x.argmin()

tensor(0)

In [66]:
x.argmax()

tensor(9)

In [70]:
#reshaping, squeezing, unsqueezing and stacking tensors

y = torch.arange(1.,11.)
y

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [71]:
#add an extra dimention

yreshaped = y.reshape(2,5)
yreshaped

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [74]:
#change view

z = x.view(1,10)
z

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [77]:
# stack tensors

x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])